### ISSUE TITLE
Feature: Allow Optional Extra assets on minted tokens 

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/itheumcore-elrond-data-nft-minter#84]
For this change needed for the SDK and Data DEX, we need a smart contract upgrade as well.
https://github.com/Itheum/sdk-mx-data-nft/issues/125

PR is ready here:
https://github.com/Itheum/itheumcore-elrond-data-nft-minter/pull/83

**Comment by damienen** [comment]
Solved. Closing
